[package]
name = "memif"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "^1.0.42"
uds = "*"
binary_serde = { version = "*", features = ["std"] }
memfd = "*"
nix = { version = "*", features = ["fs", "mman", "uio", "socket", "event"] }
vcell = "*"

